# Пользователи

## Регистрация пользователя
POST http://localhost:5555/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Dima",
  "email": "2@2.ru",
  "password": "qwerty123"
}

###

## Авторизация пользователя
POST http://localhost:5555/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "dima@test.ru",
  "password": "qwerty123"
}

###

## Проверка токена пользователя
GET http://localhost:5555/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRpbWFAdGVzdC5ydSIsImlkIjoiNjQ4YTBmM2Y5ZTQwNDJmMjVmNTYxZTc5IiwiaWF0IjoxNjg3MjIzNTAwLCJleHAiOjE2ODczOTYzMDB9.IMCm-aIXueLCgLnlt7UjWfVlwkUlh4nL7ztfav6AwW8

###
